<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ip-172-31-27-153" failures="4" tests="5" name="Test" time="3.309" errors="0" timestamp="24 Feb 2024 12:27:01 GMT">
  <testcase classname="apiautomation.EmployeesAPI" name="Test_1_getAllEmployee" time="1.895"/>
  <testcase classname="apiautomation.EmployeesAPI" name="Test_2_createEmployee" time="0.336">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;429&amp;gt; but was:&amp;lt;200&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<429> but was:<200>
at apiautomation.EmployeesAPI.Test_2_createEmployee(EmployeesAPI.java:43)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Test_2_createEmployee -->
  <testcase classname="apiautomation.EmployeesAPI" name="Test_3_getOneEmployee" time="0.354">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;429&amp;gt; but was:&amp;lt;200&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<429> but was:<200>
at apiautomation.EmployeesAPI.Test_3_getOneEmployee(EmployeesAPI.java:61)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Test_3_getOneEmployee -->
  <testcase classname="apiautomation.EmployeesAPI" name="Test_4_deleteEmployee" time="0.316">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;429&amp;gt; but was:&amp;lt;200&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<429> but was:<200>
at apiautomation.EmployeesAPI.Test_4_deleteEmployee(EmployeesAPI.java:78)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Test_4_deleteEmployee -->
  <testcase classname="apiautomation.EmployeesAPI" name="Test_5_deleteDeletedEmployee" time="0.385">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;429&amp;gt; but was:&amp;lt;200&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<429> but was:<200>
at apiautomation.EmployeesAPI.Test_5_deleteDeletedEmployee(EmployeesAPI.java:94)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Test_5_deleteDeletedEmployee -->
</testsuite> <!-- Test -->
